#!/bin/bash

for f in `ls $1/*`; do
    echo "$f:"
    timeout 1 ./consistency $f -s | grep -v "Presaturation"
    echo
    echo "------------------------------------------------------------------"
done