#!/bin/bash

PROGRAM="eprover"

if [ -z $2 ]; then
    FLAG=""
else
    if [ $2 == "eproof" ]; then
        PROGRAM="eproof"
        FLAG=""
    else
        FLAG=$2
    fi
fi

OUTFILE=tmp/`basename $1.tptp`

autospec $1 > $OUTFILE

if [ $? == 0 ]; then
    $PROGRAM -tAuto -xAuto --tptp3-format --memory-limit=1000 $FLAG $OUTFILE
else
    cat $OUTFILE
fi