#!/bin/bash

PROGRAM="eprover"

if [ -z $2 ]; then
    FLAG=""
else
    if [ $2 == "eproof" ]; then
        PROGRAM="eproof"
        FLAG=""
    else 
        FLAG=$2
    fi
fi

./Translate $1 > `basename $1.tptp` && \
   $PROGRAM -tAuto -xAuto --tptp3-format $FLAG `basename $1.tptp`