
* TODO Fixes
** DONE merge Expr and BoolExpr
CLOSED: [2012-02-02 Thu 13:31]
- State "DONE"       from ""           [2012-02-02 Thu 13:31]
** rename NobodyExpectsTheScottInduction
** maybe try some other sorting (selection sort, merge sort)
** TODO Cannot do structural induction on Expressions. Need to fix this

* Bool
Various simple properties about &&, || and not from quickspec
* BoolLists
nub idempotency for Bool lists. This is a theorem for cototal values
* Expr
Nat and bool expressions with properties about mirror, size and eval
* Fix
Even and odd defined in different ways using fix
* Functions
Properties only related to functions such as function composition, currying
* Infinite
Propertes that hold for infinite lists and trees
* IWC
Some hard properties from a
http://www.csc.liv.ac.uk/~lad/research/challenges
inductive challenges
* ZenoLists
The list part of Zeno's test suite
* Reverse
Properties about reverse with and without accumulator
* MonadEnv
Properties for the environment monad. Good for testing app and lambda lifting
* MonadMaybe
Properties of the maybe monad
* MonadState
Properties for the state monad
* Nat
Properties about natural numbers from the Zeno test suite
* Nat2ndArg
Induction on the second argument instead
* NatAcc
Nat but with plus and multiplication expressed with an accumulator
* NatBot
Plus and multiplication strict in both arguments
* NatDouble
Pattern matching in two depth for plus and multiplication
* NatDoubleStupid
Pattern matching in two depth, but only recusing into one depth
* NatSwap
Addition and multiplication with arguments swapped in the recursive call
* NobodyExpectsTheScottInduction
Some properties interesting for fixed point induction
* Ordinals
Brouwer ordinals as defined in Dixon's thesis
* PAP
Properties with partially applied functions
* PatternMatchingDifferences
Or and mirror defined in different ways and properties that state
their equality
* ProductiveUseOfFailure
From the paper with the same name. These properties need lemmas or
generalizations and most are currently not provable.
* Queues
Queues with O(1) pop and enqueue. Has a problematic invariant and
equality and hence a lot of properties are not currently provable.
* Sequences
Some properties about infinite sequences
* InsertionSort
Insertion sort on nat and bool lists
* MergeSort
Merge sort on bool lists
* Streams
Some properties about stream from Hinze's paper Concrete Stream Calculus
* Patterns
A test on the pattern matching. This is how an auto generated test of
pattern matchings should look like. Not included.
* Mini
A few properties from other sets. This should not be included in the
test suite
